version: "3.7"

services:
    web:
        image: cleaningladylist
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/cleaningladylist.com:delegated
        tmpfs:
            - /var/www/cleaningladylist.com/var/cache
        depends_on:
            - mysql

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8094:8080
        depends_on:
            - mysql

    # https://hub.docker.com/_/mysql
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "cleaningladylist_com"
        volumes:
            - ./.docker/mysql-data:/var/lib/mysql
        ports:
            - 3350:3306
