#!/bin/bash
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

composer install --prefer-dist --no-progress --no-suggest --no-interaction -o

# Permissions hack because setfacl does not work on Mac and Windows
chown -R www-data var

# Continue by running original entrypoint
docker-php-entrypoint $@
