name: Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Log into registry
              # DOCKER_TOKEN get here: https://hub.docker.com/settings/security
              # DOCKER_USERNAME != email
              run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build and push image
              run: |
                  # Cache multi-stage builds: https://pythonspeed.com/articles/faster-multi-stage-builds/
                  # this image does not exist
                  docker pull rector/cleaningladylist.com:base || true
                  docker pull rector/cleaningladylist.com:node-build || true
                  docker pull rector/cleaningladylist.com:latest || true

                  docker build . --tag rector/cleaningladylist.com:base --target base \
                    --cache-from rector/cleaningladylist.com:base

                  docker build . --tag rector/cleaningladylist.com:node-build --target node-build \
                    --cache-from rector/cleaningladylist.com:base \
                    --cache-from rector/cleaningladylist.com:node-build

                  docker build . --tag rector/cleaningladylist.com:latest --target production \
                    --build-arg commitHash=${{ github.sha }} \
                    --cache-from rector/cleaningladylist.com:base \
                    --cache-from rector/cleaningladylist.com:node-build \
                    --cache-from rector/cleaningladylist.com:latest

                  docker push rector/cleaningladylist.com:base
                  docker push rector/cleaningladylist.com:node-build
                  docker push rector/cleaningladylist.com:latest

            # see https://github.com/appleboy/ssh-action
            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  # e.g. cleaningladylist.com
                  host: ${{ secrets.DEPLOY_HOST }}
                  # usually "root"
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  # always private key
                  key: ${{ secrets.DEPLOY_KEY }}
                  script: "cd /projects/cleaningladylist.com && ./run.sh"
