name: "Docker Local Run"

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build
              run: |
                  cd /cleaningladylist.com
                  docker-compose build
