# only for testing that Dockerfile is build correctly
name: Docker Build

# this should run only on pull-request (fix after this works)
on: push

jobs:
    warmup:
        name: Cache warmup
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build image
              run: |
                  docker pull rector/cleaningladylist.com:latest || true

                  docker build . --tag image --cache-from rector/cleaningladylist.com:latest

            - name: Warmup cache
              run: docker run -e APP_ENV=prod image bin/console cache:warmup

            - name: Doctrine schema validation
              run: docker run -e APP_ENV=prod image bin/console doctrine:schema:validate --skip-sync
