name: PHPStan

on: push

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: shivammathur/setup-php@v1
          with:
            php-version: 7.4
            coverage: none

      -   run: composer install --no-progress
      -   run: vendor/bin/phpstan analyse src