name: Production build

on: push

jobs:
    warmup:
        name: Cache warmup
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build image
              run: |
                  # Cache multi-stage builds: https://pythonspeed.com/articles/faster-multi-stage-builds/

                  docker pull rector/cleaningladylist.com:base || true
                  docker pull rector/cleaningladylist.com:node-build || true
                  docker pull rector/cleaningladylist.com:latest || true

                  docker build . --tag image --target production \
                    --cache-from rector/cleaningladylist.com:base \
                    --cache-from rector/cleaningladylist.com:node-build \
                    --cache-from rector/cleaningladylist.com:latest

            - name: Warmup cache
              run: docker run -e APP_ENV=prod image bin/console cache:warmup

            - name: Doctrine schema validation
              run: docker run -e APP_ENV=prod image bin/console doctrine:schema:validate --skip-sync
